server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/certificate.p12
  key-store-password: password
#  key-alias: localhost

server.port: 8080

spring.application.name: gateway
spring.config.import: "configserver:"
app.config-server: localhost
allowed.origin: http://localhost:3000,https://travelnow.vercel.app/

jwt:
  signing-secret: secret

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  gateway:
    excludedURLsNew: /api/v1/users/authenticate,/login,/register
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://${app.config-server}:8888

---
spring.config.activate.on-profile: docker

app.config-server: config-server

