server.port: 8080

spring.application.name: gateway
spring.config.import: "configserver:"
app.config-server: localhost
app.database: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  signing-secret: secret

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

security.enable-csrf: false
spring:
  gateway:
    excludedURLsNew: /api/v1/users/authenticate,/login
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: jdbc:postgresql://${app.database}:5432/test_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://${app.config-server}:8888
  security:
    enable-csrf: false

---
spring.config.activate.on-profile: docker

app.config-server: config-server
app.database: postgres

