DROP SEQUENCE IF EXISTS "request_sequence";
DROP SEQUENCE IF EXISTS "finance_sequence";

CREATE SEQUENCE "request_sequence"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
NOCYCLE;


CREATE SEQUENCE "finance_sequence"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
NOCYCLE;
