DROP SEQUENCE IF EXISTS "day_sequence";
DROP SEQUENCE IF EXISTS "attraction_sequence";
CREATE SEQUENCE "day_sequence"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
NOCYCLE;

CREATE SEQUENCE "attraction_sequence"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
NOCYCLE;